apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db-redis
  name: db-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    io.kompose.service: db-redis
  type: ClusterIP