apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: service-rsshub
  name: service-rsshub
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: "1200"
    port: 1200
    protocol: TCP
    targetPort: 1200
  selector:
    io.kompose.service: service-rsshub
  type: LoadBalancer