apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: service-browserless
  name: service-browserless
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    io.kompose.service: service-browserless
  type: ClusterIP