apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: service-rsshub
  name: service-rsshub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-rsshub
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: service-rsshub
    spec:
      containers:
      - env:
        - name: CACHE_TYPE
          value: redis
        - name: NODE_ENV
          value: production
        - name: PUPPETEER_WS_ENDPOINT
          value: ws://service-browserless:3000
        - name: REDIS_URL
          value: redis://db-redis:6379/
        image: diygod/rsshub
        imagePullPolicy: Always
        name: service-rsshub
        ports:
        - containerPort: 1200
          protocol: TCP
      restartPolicy: Always