apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db-redis
  name: db-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-redis
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db-redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: db-redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data