
#TODO 动态存储卷没有测试。
#TODO 静态存储卷没有成功过。
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    io.kompose.service: redis-data
  name: redis-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  # 根据环境不同需要修改，云上一般为disk，本地cluster一般为hostpath
  storageClassName: disk